name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          shellcheck bin/*

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: ['1.13.0', 'latest']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install asdf
        uses: asdf-vm/actions/setup@v3

      - name: Install dependencies (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake flex bison

      - name: Install dependencies (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install cmake flex bison

      - name: Get latest version
        if: matrix.version == 'latest'
        id: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          LATEST=$(./bin/list-all | tr ' ' '\n' | head -1)
          echo "version=${LATEST}" >> $GITHUB_OUTPUT

      - name: Test plugin with specific version
        if: matrix.version != 'latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          asdf plugin test doxygen . --asdf-plugin-gitref ${{ github.sha }} --asdf-tool-version ${{ matrix.version }} doxygen --version

      - name: Test plugin with latest version
        if: matrix.version == 'latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          asdf plugin test doxygen . --asdf-plugin-gitref ${{ github.sha }} --asdf-tool-version ${{ steps.latest.outputs.version }} doxygen --version
